server:
  port: 10088
#给当前的工程起一个唯一标识,名字不能包含下划线
spring:
  application:
    name: eureka-server


#配置Eureka
eureka:
  client:
    #配置Eureka注册中心的地址
    service-url:
      defaultZone: http://localhost:10088/eureka
      #配置当前的注册中心不能获取其他的微服务地址
    fetch-registry: false
